### PR TITLE
Sendmail suid

### PR DESCRIPTION
**Pull request by drzraf**
try to address #2

### CODE REVIEW

**Comment by shuber2** [comment]
Sorry for not replying for such a long time. Could you split the sendmail merge into a separate commit, so I could merge this commit at least.

The other thing regarding nuitka3 and issue #2  is something I do not entirely understand at the moment.

**Comment by drzraf** [comment]
The SUID rule of the Makefile is not run by default. It's really safe to merge even though one may not want to go that way nor run `make suid` (but it's still handle and informative)

**Comment by shuber2** [comment]
Hi,

could you please reorganize this pull request into logically coherent pieces to keep the history clean:

1. A pull request with a commit that integrates the sendmail script into the smailq python program.
2. A pull request that introduces the suid Makefile target.

A separate commit with the .gitignore entries could be part of the second pull request.


Thank you for your contributes,
Stefan

**Comment by shuber2** [comment]
I thought again about your use case. Your argument is essentially based on those two premises:
1. You have a couple of users (e.g., php, www-data) that send mails through /usr/sbin/sendmail.
2. You cannot or would not like to setup smailq for all those users.

From that you conclude:
1. The sendmail should be suid, which would then call smailq with uid=root, for which you configure smailq.
2. Since shell scripts cannot be suid you merge the sendmail script into smailq.
3. Since pythons scripts cannot be suid you pull in the dependency nuitka3 that compiles python scripts with C compilers.

The implications are:
1. A suid program constitutes a significant security risk of privilege escalation, especially with the complex technology stack python, nuitka3, smailq and the underyling MSA (e.g., msmstp).
2. Now sendmail is always executed as root user and per-user configuration of smailq (and the underlying MSA, like msmtp) are inhibited.
3. A significant technical dept, nuitka3, is pulled in.

By replacing the shell script `sendmail` by a C program, we eliminate implication 3 and we avoid that smailq itself acts as sendmail. This is also slight improvement regarding implication 1.

Finally, the question is whether we can eliminate implications 2 somehow. For instance, can we provide two versions of sendmail (suid and non-suid)? On different paths? By different names like `sendmail` and `sendmail.nosuid`? Does that make sense? In mutt we can set the sendmail binary, e.g., to `sendmail.nosuid`. Can you also do such a thing for your use cases, which would allow to have the suid version been installed as `/usr/sbin/sendmail.suid` or such? The latter would have the nice upside that the suid-version would be an incremental add on rather than a change of existing behavior.

**Comment by shuber2** [comment]
I have replaced the sendmail shell script by a C implementation, see master branch.

Could you (@drzraf ) share your thoughts the the remaining issue, i.e., tackling implication 2?

**Pull request closed without merging**
